# Classes
class CalorieCounter
  @file: String
  @_calorie_list: Hash[Integer, String]

  def initialize: (String file) -> void
  def most_food: -> Integer
  def calorie_list: -> Hash[Integer, String]

  private
  def parsed_data: -> Hash[Integer, String]
end
